version: "3.9"
services:

  mariadb:
    container_name: mariadb
    init: true
    build: ./requirements/mariadb
    networks:
      - inception-network
    environment:
      - COMPOSE_PROJECT_NAME
    volumes:
      - db_data:/var/lib/mysql/
    # restart: always

  wordpress:
    container_name: wordpress
    init: true
    build: ./requirements/wordpress
    networks:
      - inception-network
    environment:
      - COMPOSE_PROJECT_NAME
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html/
    # restart: always

  nginx:
    container_name: nginx
    init: true
    build: ./requirements/nginx
    networks:
      - inception-network
    environment:
      - COMPOSE_PROJECT_NAME
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html/
    # restart: always

networks:
  inception-network:
    name: inception-network
    driver: bridge

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /home/mberne/data/db
      o: bind
      type: none
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      device: /home/mberne/data/wp
      o: bind
      type: none
